<a href="https://colab.research.google.com/github/hongjai-rhee/public/blob/master/%EB%9E%9C%EB%8D%A4%ED%8F%AC%EB%A0%88%EC%8A%A4%ED%8A%B8_%EB%B6%84%EB%A5%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 랜덤 포레스트 분류 모형
X에서 랜덤으로 추출된 부분집합 x변수에 의해 y변수의 클래스를 구분하는 decision tree를 K개 만든 다음, 주어진 X에 대한 K개 예측치를 다수결로 평가하여 최종 예측을 하는 알고리즘. 똑똑한 한 명보다 조금 덜 똑똑한 100명이 더 낫다는 멋진 아이디어. 
https://medium.com/@deepvalidation/title-3b0e263605de
 
 


# 아이리스 데이타를 불러오자. 

In [67]:
import pandas as pd; from sklearn import datasets

iris = datasets.load_iris()
data.head()#species (품종)는 3개의 카테고리를 가진다(0/1/2)

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

# 훈련과 검증 데이터를 분리한다.

In [68]:
from sklearn.model_selection import train_test_split; import random
random.seed(155)
 
x = data[['sepal length', 'sepal width', 'petal length', 'petal width']]
y = data['species']
 
# 테스트 데이터 30%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)


(105, 4) (45, 4) (105,) (45,)


# 학습을 하고, 예측을 한다.

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
# 학습 진행
n_tree =100   ## 의사결정 나무의 수
forest = RandomForestClassifier(n_estimators=n_tree)
forest.fit(x_train, y_train)
# 예측
y_pred = forest.predict(x_test)
print("실제",list(y_test))
print("예측",list(y_pred))



실제 [1, 1, 0, 2, 2, 0, 0, 2, 2, 0, 1, 2, 2, 2, 1, 0, 1, 2, 0, 0, 2, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 0, 1]
예측 [1, 1, 0, 2, 2, 0, 0, 2, 2, 0, 1, 2, 2, 2, 1, 0, 1, 2, 0, 0, 2, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 0, 1]


# 검증데이터에 대한 예측력을 살펴보자

In [70]:
# 정확도 확인
acc= metrics.accuracy_score(y_test, y_pred)
import matplotlib.pyplot as plt; import numpy as np; from sklearn.metrics import confusion_matrix
print("test accuracy=",  np.round(100*acc,2), "%")
print("Confusion Matrix")
print("*****************")
print(confusion_matrix(y_test, y_pred))   ## 대각선이 올바른 예측



test accuracy= 100.0 %
Confusion Matrix
*****************
[[16  0  0]
 [ 0 13  0]
 [ 0  0 16]]
