<a href="https://colab.research.google.com/github/hongjai-rhee/public/blob/master/%EB%B8%8C%EB%9E%9C%EB%93%9C%EC%84%A0%ED%83%9D_%EB%9E%9C%EB%8D%A4%ED%8F%AC%EB%A0%88%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 브랜드 선택모형을 랜덤 포레스트로 돌려보자
전에 했던 브랜드 선택과 동일한 데이터, ‘choice500.csv’를 불러온다. 


In [14]:
data_file='choice500.csv'    ## 데이터 파일 이름

## 필요한 라이브러리 불러오기
import pandas as pd; import numpy as np; from keras.models import Sequential; from keras.layers import Dense, Dropout, Activation; import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split; from keras.utils.np_utils import to_categorical;  from matplotlib import style

## 데이터 불러오기  
dat = pd.read_csv(data_file); dat = np.array(dat); ncol=dat.shape[1]; nrow=dat.shape[0]
x=dat[:,0:ncol-1]; y=dat[:,ncol-1]-1; y = to_categorical(y)

## 데이터 살펴보기  
print(np.around(x[0:10,:],2))      # 고객특성(나이, 성별, 헤비유저), 3개 브랜드의 (가격, 광고, 스페셜 디스플레이 여부)
print(y[0:10])                     # 선택된 브랜드  
class_names = ['nabisco', 'keebler', 'sunshine']    ## 브랜드 이름

[[29.    1.    1.    1.65  1.43  1.66  1.    1.    1.    0.    0.    1.  ]
 [30.    1.    1.    1.62  1.53  1.76  0.    0.    0.    1.    0.    0.  ]
 [53.    1.    1.    1.52  1.53  1.76  1.    0.    1.    1.    1.    1.  ]
 [55.    0.    0.    1.83  1.62  1.67  1.    0.    1.    0.    0.    0.  ]
 [57.    0.    0.    1.86  1.63  1.72  1.    0.    0.    0.    1.    1.  ]
 [31.    0.    1.    1.64  1.85  1.62  0.    0.    1.    1.    1.    0.  ]
 [30.    1.    0.    1.75  1.67  1.78  1.    1.    1.    0.    0.    1.  ]
 [37.    1.    1.    1.87  1.37  1.77  1.    1.    0.    1.    1.    1.  ]
 [44.    1.    0.    1.76  1.9   1.74  0.    0.    1.    0.    1.    0.  ]
 [26.    1.    1.    1.67  1.39  1.65  0.    0.    1.    1.    1.    1.  ]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


# 훈련과 검증 데이터를 분리한 후, 학습을 하고, 예측을 한다.

In [15]:
from sklearn.model_selection import train_test_split; import random
random.seed(155)
 
# 테스트 데이터 30%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)


from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics    
 
# 학습 진행
n_tree =100   ## 의사결정 나무의 수
forest = RandomForestClassifier(n_estimators=n_tree)
forest.fit(x_train, y_train)
# 예측
y_pred = np.argmax(forest.predict(x_test), axis=1)
y_true= np.argmax(y_test, axis=1)
print("실제",list(y_true))
print("예측",list(y_pred))

실제 [2, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 1, 0, 0, 2, 1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 1, 1]
예측 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 1, 2, 0, 1, 1, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 2, 1, 2, 1, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 1, 1]


# 검증데이터에 대한 예측력을 살펴보자.
랜덤 포레스트는 여러 개의 모형이 collaborate하는 ensemble 모형이므로 예측력이 훨씬 좋아짐을 알 수 있다. How brilliant it is! 


In [16]:
# 정확도 확인
acc= metrics.accuracy_score(y_true, y_pred)
import matplotlib.pyplot as plt; import numpy as np; from sklearn.metrics import confusion_matrix
print("test accuracy=",  np.round(100*acc,2), "%")
print("Confusion Matrix")
print("*****************")
print(confusion_matrix(y_true, y_pred))   ## 대각선이 올바른 예측

test accuracy= 88.0 %
Confusion Matrix
*****************
[[77  1  1]
 [ 7 29  0]
 [ 8  1 26]]
